// Ported from backend/server.js and tuned against real tag data; do not
// "tidy" these lists without re-testing.

export const MUSICBRAINZ_NON_GENRE: readonly string[] = [
  "favorite",
  "favorites",
  "favourites",
  "love",
  "loved",
  "awesome",
  "great",
  "good",
  "best",
  "top",
  "epic",
  "amazing",
  "perfect",
  "classic",
  "old",
  "new",
  "recent",
  "popular",
  "hit",
  "single",
  "album",
  "track",
  "song",
  "music",
  "band",
  "artist",
  "group",
  "male vocals",
  "female vocals",
  "vocals",
  "guitar",
  "bass",
  "drums",
  "seen live",
];

export const GENRE_COMBINATIONS: Record<string, Record<string, string>> = {
  "punk": { "rock": "Punk Rock", "alternative": "Alternative Punk" },
  "alternative": { "rock": "Alternative Rock", "metal": "Alternative Metal" },
  "indie": { "rock": "Indie Rock", "pop": "Indie Pop", "folk": "Indie Folk" },
  "hard": { "rock": "Hard Rock" },
  "progressive": { "rock": "Progressive Rock", "metal": "Progressive Metal" },
  "folk": { "rock": "Folk Rock" },
  "pop": { "rock": "Pop Rock", "punk": "Pop Punk" },
  "synth": { "pop": "Synth-Pop", "wave": "Synthwave" },
  "new": { "wave": "New Wave" },
  "dream": { "pop": "Dream Pop" },
  "conscious": { "hip hop": "Conscious Hip Hop", "rap": "Conscious Rap" },
  "gangsta": { "rap": "Gangsta Rap" },
  "old school": { "hip hop": "Old School Hip Hop" },
  "country": { "rock": "Country Rock" },
  "alt": { "country": "Alt Country" },
  "neo": { "soul": "Neo Soul" },
  "contemporary": { "r&b": "Contemporary R&B" },
  "motown": { "soul": "Motown" },
  "northern soul": { "soul": "Northern Soul" },
  "bebop": { "jazz": "Bebop" },
  "smooth jazz": { "jazz": "Smooth Jazz" },
  "fusion": { "jazz": "Fusion" },
  "swing": { "jazz": "Swing" },
};
