// Ported verbatim from backend/server.js. These tables were tuned against
// real Last.fm tag data; do not "tidy" the numbers without re-testing.

/** Higher score wins. Specific subgenres beat generic ones. */
export const GENRE_PRIORITY: Record<string, number> = {
  "punk rock": 20,
  "pop punk": 19,
  "grunge": 19,
  "indie rock": 18,
  "alternative rock": 18,
  "progressive rock": 18,
  "hard rock": 17,
  "classic rock": 17,
  "psychedelic rock": 17,
  "garage rock": 17,
  "post-punk": 17,
  "new wave": 17,
  "indie pop": 18,
  "synth-pop": 17,
  "dream pop": 17,
  "shoegaze": 17,
  "britpop": 17,
  "folk rock": 16,
  "southern rock": 16,
  "glam rock": 16,
  "art rock": 16,
  "heavy metal": 18,
  "thrash metal": 18,
  "death metal": 18,
  "black metal": 18,
  "power metal": 17,
  "progressive metal": 17,
  "doom metal": 17,
  "nu metal": 17,
  "house": 16,
  "techno": 16,
  "trance": 16,
  "drum and bass": 16,
  "dubstep": 16,
  "ambient": 16,
  "downtempo": 15,
  "trip hop": 15,
  "idm": 15,
  "gangsta rap": 17,
  "conscious hip hop": 17,
  "trap": 16,
  "old school hip hop": 16,
  "underground hip hop": 16,
  "neo soul": 16,
  "contemporary r&b": 15,
  "motown": 16,
  "northern soul": 15,
  "country rock": 16,
  "alt country": 16,
  "bluegrass": 16,
  "honky tonk": 15,
  "bebop": 16,
  "smooth jazz": 15,
  "fusion": 15,
  "swing": 15,
  "alternative": 14,
  "indie": 13,
  "punk": 14,
  "metal": 13,
  "electronic": 12,
  "hip hop": 12,
  "rap": 12,
  "r&b": 11,
  "soul": 11,
  "funk": 11,
  "reggae": 11,
  "ska": 12,
  "blues": 11,
  "folk": 10,
  "country": 10,
  "jazz": 10,
  "classical": 10,
  "world": 9,
  "rock": 8,
  "pop": 7,
  "dance": 6,
  "vocal": 4,
  "singer-songwriter": 8,
  "acoustic": 5,
  "instrumental": 4,
  "soundtrack": 3,
  "experimental": 6,
};

/** Tags that are not genres. Matched as substrings, as in the original. */
export const MUSICBRAINZ_NON_GENRE: readonly string[] = [
  "favorite",
  "favorites",
  "favourites",
  "love",
  "loved",
  "awesome",
  "great",
  "good",
  "best",
  "top",
  "epic",
  "amazing",
  "perfect",
  "classic",
  "old",
  "new",
  "recent",
  "popular",
  "hit",
  "single",
  "album",
  "track",
  "song",
  "music",
  "band",
  "artist",
  "group",
  "male vocals",
  "female vocals",
  "vocals",
  "guitar",
  "bass",
  "drums",
  "seen live",
];

export const LASTFM_NON_GENRE: readonly string[] = [
  "seen live",
  "favorite",
  "loved",
  "favorites",
  "love",
  "awesome",
  "great",
  "good",
  "best",
  "top",
  "epic",
  "amazing",
  "perfect",
  "classic",
  "old",
  "new",
  "recent",
  "popular",
  "hit",
  "single",
  "album",
  "track",
  "song",
  "music",
  "band",
  "artist",
  "group",
  "male",
  "female",
  "vocals",
  "guitar",
  "bass",
  "drums",
  "american",
  "british",
  "english",
  "uk",
  "usa",
  "canadian",
  "90s",
  "80s",
  "70s",
  "2000s",
  "2010s",
];

/** "punk" + "rock" reads better as "Punk Rock". */
export const GENRE_COMBINATIONS: Record<string, Record<string, string>> = {
  "punk": { "rock": "Punk Rock", "alternative": "Alternative Punk" },
  "alternative": { "rock": "Alternative Rock", "metal": "Alternative Metal" },
  "indie": { "rock": "Indie Rock", "pop": "Indie Pop", "folk": "Indie Folk" },
  "hard": { "rock": "Hard Rock" },
  "progressive": { "rock": "Progressive Rock", "metal": "Progressive Metal" },
  "folk": { "rock": "Folk Rock" },
  "pop": { "rock": "Pop Rock", "punk": "Pop Punk" },
  "synth": { "pop": "Synth-Pop", "wave": "Synthwave" },
  "new": { "wave": "New Wave" },
  "dream": { "pop": "Dream Pop" },
  "conscious": { "hip hop": "Conscious Hip Hop", "rap": "Conscious Rap" },
  "gangsta": { "rap": "Gangsta Rap" },
  "old school": { "hip hop": "Old School Hip Hop" },
  "country": { "rock": "Country Rock" },
  "alt": { "country": "Alt Country" },
  "neo": { "soul": "Neo Soul" },
  "contemporary": { "r&b": "Contemporary R&B" },
  "motown": { "soul": "Motown" },
  "northern soul": { "soul": "Northern Soul" },
  "bebop": { "jazz": "Bebop" },
  "smooth jazz": { "jazz": "Smooth Jazz" },
  "fusion": { "jazz": "Fusion" },
  "swing": { "jazz": "Swing" },
};
